version: '3'
services:
  db:
    image: mongo
    volumes:
      - ./tmp/db:/var/lib/mongo/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/drop_token
    ports:
      - "3000:3000"
    depends_on:
      - db